enum MessageTypeEnum {
  HANDSHAKE = "TYPE_HANDSHAKE",
  CREATE_TRANSACTION = "TYPE_CREATE_TRANSACTION",
  PUBLISH_BLOCK = "TYPE_PUBLISH_BLOCK",
  REQUEST_BLOCK = "REQUEST_BLOCK",
  SEND_BLOCK = "SEND_BLOCK",

  // DEPRECATED
  REQUEST_CHAIN = "TYPE_REQUEST_CHAIN",
  SEND_CHAIN = "TYPE_SEND_CHAIN",
}

export { MessageTypeEnum }
